name: Build
on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/steps/install-gradle.yml
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0
